### ISSUE TITLE
Library doesn't seem to account for permissions?

### ISSUE THREAD

**Issue by Gear61** [filestack/filestack-android#111]
Starting with Android Marshmallow (API level 23+), you have to request permissions on run-time as opposed to gaining them all on app install. I just tried using the camera option for your library and it crashed with a SecurityException instead of requesting the proper permission.

**Comment by Gear61** [comment]
If you need help incorporating the new Android M permissions, I personally found this article to be very helpful: https://inthecheesefactory.com/blog/things-you-need-to-know-about-android-m-permission-developer-edition/en

**Comment by shawnmaten** [comment]
Just as with issue #114, we're going to touch this with a major update that'll begin after completing a new Java SDK.

**Comment by Gear61** [comment]
@lifalzarano

Tagging my coworker at Course Hero because I don't work there anymore.

**Comment by shawnmaten** [comment]
Closing this as it's no longer relevant for v2.
