### ISSUE TITLE
Authenticate with Google through the browser instead of a webview

### ISSUE THREAD

**Issue by Gear61** [filestack/filestack-android#113]
According to Google, webview Oauth support will end on April 20th of this year: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

I was wondering if there are plans to adjust this flow by then?

**Comment by emandmatt** [comment]
Also wondering if the Android SDK will support the new Google Oauth. Need to plan development and currently seeking other options.

**Comment by interactivematt** [comment]
Also wondering if the Android SDK will support the new Google Oauth. Need to plan development and currently seeking other options.

**Comment by dubsquared** [comment]
@Gear61 @interactivematt, we are currently in the process of updating both of our mobile SDK's to use Google's new auth mechanics.  We will be pushing the updates as soon as they are tested, but we do plan to have everything up and ready to go in time for the cutover.

**Comment by shawnmaten** [comment]
This is supported as of version 4.0.1. Please be mindful of the new instructions for setup at the bottom of the README, you will need Google API access. Let us know if you encounter any issues or have any questions.
