### ISSUE TITLE
Update company images/logos

### ISSUE THREAD

**Issue by Gear61** [filestack/filestack-android#114]
I think it would be awesome if we could at the very least upgrade the logos from black/white. Also, Box's logo seems to be incorrect. It kind of looks like the Microsoft logo?

**Comment by shawnmaten** [comment]
We'll soon begin a major update to the Android SDK with an updated UI. This issue will get fixed as part of that. Our next step is to create a new underlying Java SDK, then we'll begin significant updates to this SDK.

**Comment by Gear61** [comment]
@lifalzarano

**Comment by shawnmaten** [comment]
Closing this as it's no longer relevant for v2. We use vector logos now. 👍 (Although IMHO they could be prettier.)
