### ISSUE TITLE
Getting unique key (key) null

### ISSUE THREAD

**Issue by nishantsh** [filestack/filestack-android#115]
Hey,
I am using the file picker for choosing images/videos/pdfs etc from various drives.
For the case when I'am selecting images I get all the details in FPFile but when I select other files like any pdf or some docx file, I'am getting the key field null.
Please help.

Thanks in advance.

**Comment by shawnmaten** [comment]
I'm going to look into why this isn't being set, but as a workaround you can get the key from the end of the url. I've included an example that uses a regular expression and the Java Pattern class.

```java
FPFile file = fpFiles.get(0);
Pattern pattern = Pattern.compile("\\Qhttps://cdn.filepicker.io/api/file/\\E(.+)");
Matcher matcher = pattern.matcher(file.getUrl());
matcher.find();
String imageKey = matcher.group(1);
```

**Comment by shawnmaten** [comment]
Could you provide some more information on what you're doing to reproduce this? If you've configured your own S3 storage, the FPFile object should have a populated key. You're saying this is only happening when you upload images and never happening when you upload other file types?

**Comment by nishantsh** [comment]
Thanks for your reply. 
I configured my S3 storage and then after some workaround i was able to get all the details for each type of file.

**Comment by shawnmaten** [comment]
When you say "after some workaround", were you still having issues with FPFile being populated?

**Comment by nishantsh** [comment]
After some workaround means that I tried the storage option at last. That's it.
Thanks.
