### ISSUE TITLE
Error with authorization

### ISSUE THREAD

**Issue by worstkiller** [filestack/filestack-android#123]
Hey Guys
This is basically more of question if i'am doing something wrong.
After intialization and putting key into 
```
      ```
  Filepicker.setKey(WebConstants.FILE_STACK_API_KEY);
        Filepicker.setAppName("Android");
```


and after that i am calling by

   ```
Intent intent = new Intent(getActivity(), Filepicker.class);
        intent.putExtra("multiple", true);
        startActivityForResult(intent, Filepicker.REQUEST_CODE_GETFILE);
```

```
now the problem is the error which i am getting of authorization
but our web team is using this key successful
now please tell me what is going wrong,

**Comment by shawnmaten** [comment]
Can you provide the log output with the error?

**Comment by worstkiller** [comment]
thanks man for replying back, filestack support team was able to help me on that.
Thanks
