### ISSUE TITLE
Error after Google Services authorization.

### ISSUE THREAD

**Issue by Lukkub** [filestack/filestack-android#125]
After success google services authorization Picker is closed with such error:
```
'Error: FileStack didFinishPickingMediaCallback', { [Error: 0] framesToPop: 1, code: 'E_NO_IMAGE_DATA_FOUND' }
```
And currently every time when I select google services (drive, photos, gmail) Picker is Immediately close and above error occurs.
Not sure what is the reason.
Maybe your google services integration instruction is not full ? Maybe I missed something in configuration that is important but is not written in your docs.

Please check if u have the same issue, and let me know.

**Comment by shawnmaten** [comment]
It sounds like you have possibly not setup Google API access. Have you followed the instructions in the README under "Enabling APIs for Google Services"?
