### ISSUE TITLE
onFileUploadSuccess is not called immediately after onFileUploadProgress is 100% (1.0)

### ISSUE THREAD

**Issue by kuraneabhijit** [filestack/filestack-android#126]
Hi ,
I observed that there is lag of few seconds to get a callback for onFileUploadSuccess  after the onFileUploadProgress is 100%.
Please let me know if this issue has been observed at your side too.

--
Thanks,
Abhijit

**Comment by shawnmaten** [comment]
I'm seeing about a 1 second delay between the last call to progress and success. As I said in your other issue, we're currently working on a new Java SDK and a major update to the Android SDK. In the meantime an issue like this is going to remain. I'm curious what use case you have that this is causing you problems?

**Comment by shawnmaten** [comment]
Closing this as it's no longer relevant for v2.
