### ISSUE TITLE
onFileUploadSuccess and onFileUploadError are not called on UI thread.

### ISSUE THREAD

**Issue by kuraneabhijit** [filestack/filestack-android#127]
Hi,
It seems that the callbacks onFileUploadError and onFileUploadSuccess are called on worker thread of IntentService.
I'm receiving the crash saying Looper.prepare() not called.
Please check and let me know if I'm doing something wrong at my end in these callbacks.
Actually I'm just showing the custom toast in these callbacks.

--
Thanks,
Abhijit

**Comment by shawnmaten** [comment]
Yes I can confirm this behavior. We're planning to fix this in a major update of the Android SDK that's in progress. If you're just looking to upload local files, we're set to publish an updated Java SDK this month that will have that ability. The new Java SDK is part of the Android SDK update, taking over the core functions.

**Comment by shawnmaten** [comment]
Closing this as it's no longer relevant for v2.
