### ISSUE TITLE
onFileUploadSuccess: Failed to retrieve FpFile from the response

### ISSUE THREAD

**Issue by retrobrain** [filestack/filestack-android#128]
Hi,
The onFileUploadSuccess is never called after onFileUploadProgress gets to 1.0 instead an there is an error shown: "onFileUploadSuccess: Failed to retrieve FpFile from the response".
I'm using the 4.0.2 version of the android SDK.

**Comment by shawnmaten** [comment]
You're getting this error because you're not setting an API Key. You need to call `Filepicker.setKey();` before you call `Filepicker.uploadLocalFile();`. In your activity's `onCreate()` method would be a reasonable place to do so.

**Comment by retrobrain** [comment]
I'm setting the key in onCreate method but after I checked it there was a typo in key.

**Comment by shawnmaten** [comment]
Yep that would also do it. You're welcome.
