### ISSUE TITLE
Get filestack cdn link before closing

### ISSUE THREAD

**Issue by minhnhatspk** [filestack/filestack-android#141]
as the title , I want to get uploaded filestack cdn link before closing filestack , please help :D

**Comment by shawnmaten** [comment]
There isn't currently a method on the FileLink class to return a CDN link, but it could make sense to add one. Right now you can get the handle though, and use that to create a URL.

`String url = "https://cdn.filestackcontent.com/" + fileLink.getHandle();`

I'm confused about the last part of your question, "before closing filestack". You should get broadcast messages back as the files are uploaded / transferred, after FsActivity closes. FsActivity is setup to close once files are selected and the upload button is clicked. You have options to customize this flow, down to writing your own FsActivity, but I'm not sure what kind of flow you want.

If you're using a version prior to v2, there won't be anymore changes to that code.

**Comment by shawnmaten** [comment]
Closing because there was no further comment.
