### ISSUE TITLE
Can't run demo and list files after authorize with Google Drive

### ISSUE THREAD

**Issue by akaipham** [filestack/filestack-android#142]
When it redirected me from Google Auth View, no files were listed as well as the screen remained states like before-auth with Google Drive.

BTW I found out that something went wrong with logic in the source code though:

In `FsActitivity.java`
```
@Override
    public void onSuccess(CloudResponse contents) {
        String authUrl = contents.getAuthUrl();

        if (authUrl != null) {
            shouldCheckAuth = true;
            CloudAuthFragment cloudAuthFragment = CloudAuthFragment.create(selectedSource, authUrl);
            FragmentManager manager = getSupportFragmentManager();
            FragmentTransaction transaction = manager.beginTransaction();
            transaction.replace(R.id.content, cloudAuthFragment);
            transaction.commit();
        } else {
            shouldCheckAuth = false;
            CloudListFragment cloudListFragment = CloudListFragment.create(selectedSource);
            FragmentManager manager = getSupportFragmentManager();
            FragmentTransaction transaction = manager.beginTransaction();
            transaction.replace(R.id.content, cloudListFragment);
            transaction.commit();
        }
    }
```
It caused auto-redirecting to auth screen and never successfully authorized with Google Drive.

Any ideas about this or am I missing something?

**Comment by shawnmaten** [comment]
Issues with refreshing the view after returning from auth were fixed in release `2.0.0-alpha.2`. If you're not using that version, try it and see if that fixes the issue. I'm not clear what you mean by "It caused auto-redirecting to auth screen and never successfully authorized with Google Drive." That sounds like a potentially different issue, but let's see if you're still having issues after updating.

**Comment by minhnhatspk** [comment]
![image](https://user-images.githubusercontent.com/21996261/34553386-c949683c-f159-11e7-971d-bf8918c4511a.png)
I have the  same problem, after authentication with Google Service , The app come back without any change.

**Comment by shawnmaten** [comment]
Are you positive that you're using version `2.0.0-alpha.2`? You should set that version in your build.gradle, perform a gradle sync, and run the app again. I'm not seeing this behavior anymore with the fixed version.

**Comment by shawnmaten** [comment]
Closing this issue since there's been no reply. If you're still having this issue feel free to comment or open a new issue.
