### ISSUE TITLE
facing null pointer exception with error in == null

### ISSUE THREAD

**Issue by edcastrohit** [filestack/filestack-android#160]
when we are trying to upload jpeg image file from my one of the samsung device at that time it throw null pointer exception with error message in == null.

i tried to find the 'in' in all files but not find this kind any variable.

so thanks if any one help on this.

**Comment by shawnmaten** [comment]
Could you please provide more detail about how you're using the library? I assume you're just launching the FsActivity class, but I want to confirm that. And could you also provide more detailed log output?

**Comment by shawnmaten** [comment]
Closing this since there's been no response. Feel free to reopen with more info.
