### ISSUE TITLE
Filepicker crashes when you try to save, share or export files. 

### ISSUE THREAD

**Issue by umair1209** [filestack/filestack-android#161]
#### Expected behavior
I added a few files files to filepicker file manager just to try how it works and then I tried to  share a file but it asked me to save the file first in order to share it so I clicked on save and I was expecting it to save the file and then let me share it. 

#### Actual behavior
When I clicked on save file, it took a lot of time and finally the application crashed. I selected both big sized and small sized files but on both occasions, the file manager crashed. 
#### How to reproduce
- Go to filepicker 
- Add a file
- Click on save file option after the file is added, the filepicker application will crash. 

* Operating system: Android 6.0.1
I am using the latest version of filepicker application. 

#### Recording Of The Bug
![20180216_214157.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518801700/oktt9udjepvqsvwhzog5.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@syedumair/filepicker-crashes-when-you-try-to-save-share-or-export-files">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by shawnmaten** [comment]
The app you're referring to has not been updated since October 21, 2015 and is not related to recent work in this repo. Thank you for bringing its existence to my attention so I can remove it. Also, I ask that you not open any further issues with a "Utopian" link on the bottom, as that's rather spammy.
